### PR TITLE
imp(charts): propagate selection start and end points to transform extension listener

### PR DESCRIPTION
**Pull request by lubarskyy**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/kanva/kanva/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Infrastructure / API changes
- [x] Other  - **Improvement**

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Pass `start` and `end` area selection points to transform extension listener.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by krzysztof-miemiec** [comment]
LGTM, yet I'd like to know what's your use case for that. I noticed a build failure because of old dependencies - at some point I'll push maintenance PR.

**Review by krzysztof-miemiec — APPROVED** [review]

**Comment by lubarskyy** [comment]
> LGTM, yet I'd like to know what's your use case for that. I noticed a build failure because of old dependencies - at some point I'll push maintenance PR.

Thanks :), the use case for this change is that we need a starting and an ending point of the selection area so that we can query a more detailed data set (in our case the starting and end points are used to extract proper timestamps). Bigger data sets, for example 1 week will have a lower resolution (each point will represents 5 minutes) than let's say a 2 days (here each point will represent 1 minute).

2021-08-05-105224_1174x653_scrot

**Comment by lubarskyy** [comment]
@krzysztof-miemiec can we merge this one? I personally don't have a write access to do it by myself. If you feel this needs some more work please let me know :)

**Comment by krzysztof-miemiec** [comment]
I'll merge it, but we have to fix the dependencies, as in current state it may not be released to npm.

**Comment by lubarskyy** [comment]
sure, will take care of dependencies maintenance asap :+1:

**Comment by krzysztof-miemiec** [comment]
I have one PR in the making - give me 3 weeks for that though, as I need to do some maintenance in Storybook.

**Comment by krzysztof-miemiec** [comment]
I have one PR in the making - give me 3 weeks for that though, as I need to do some maintenance in Storybook.

**Comment by krzysztof-miemiec** [comment]
I have one PR in the making - give me 3 weeks for that though, as I need to do some maintenance in Storybook.

**Pull request merged**
